# Generated by Django 5.1.6 on 2025-04-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ensure_hospital_field'),
        ('accounts', '0004_alter_profile_aadhaar_number'),
    ]

    operations = [
    ]
